# The World address to index.
world_address = ""
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["combat_game-TrophyProgression"] 